plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = 'BrinsWathe'
}

repositories {
	maven { url 'https://maven.ladysnake.org/releases' }
	maven { url 'https://maven.maxhenkel.de/repository/public' }
	maven { url 'https://api.modrinth.com/maven' }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"brinswathe" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-world:${project.cca_version}"
	modCompileOnly "de.maxhenkel.voicechat:voicechat-api:2.6.20"
	modCompileOnly "maven.modrinth:immersive-furniture:0.1.2+1.21.1"

	modImplementation "maven.modrinth:wathe:1.3.2-1.21.1"
	modImplementation "maven.modrinth:kinswathe:1.6.3"
	modImplementation "maven.modrinth:harpymodloader:1.2.4-h1.3"
	modImplementation "maven.modrinth:starexpress:1.3.2"
	modImplementation "maven.modrinth:yacl:3.8.2+1.21.1-fabric"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
