plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = 'BrinsWathe'
}

repositories {
	maven { url 'https://maven.ladysnake.org/releases' }
	maven { url 'https://maven.maxhenkel.de/repository/public' }
	maven { url 'https://api.modrinth.com/maven' }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"brinswathe" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
	modCompileOnly "org.ladysnake.cardinal-components-api:cardinal-components-world:${project.cca_version}"
	modCompileOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
	modCompileOnly "maven.modrinth:immersive-furniture:${project.immersive_furniture_version}"

	modImplementation "maven.modrinth:wathe:${project.wathe_version}"
	modImplementation "maven.modrinth:kinswathe:${project.kinswathe_version}"
	modImplementation "maven.modrinth:harpymodloader:${project.harpymodloader_version}"
	modImplementation "maven.modrinth:starexpress:${project.starexpress_version}"
	modImplementation "maven.modrinth:yacl:${project.yacl_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
