org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.java.home=D:/Java/zulu21.50.19-ca-jdk21.0.11-win_x64

org.gradle.configuration-cache=false

minecraft_version=1.21.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.13.0
maven_group=cn.autoforged.brinswathe

fabric_api_version=0.116.12+1.21.1
cca_version=6.1.1
endec_version=0.1.5.1
