package cn.autoforged.brinswathe;

import cn.autoforged.brinswathe.component.CompensatorComponent;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameConstants;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import java.util.ArrayList;
import java.util.Collections;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.entity.player.Player;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;

public final class CompensatorPassive {
    private static boolean resolvingRetaliation;

    private CompensatorPassive() {
    }

    public static boolean isResolvingRetaliation() {
        return resolvingRetaliation;
    }

    public static boolean tryHandle(Player victim, boolean spawnBody, Player attacker, ResourceLocation deathReason) {
        if (resolvingRetaliation || !(victim instanceof ServerPlayer serverVictim)) return false;
        if (attacker == null || attacker == victim || victim.level().isClientSide) return false;

        GameWorldComponent gameWorld = GameWorldComponent.KEY.get(victim.level());
        if (!gameWorld.isRunning() || !gameWorld.isRole(victim, BrinRoles.COMPENSATOR)) return false;
        if (!GameFunctions.isPlayerAliveAndSurvival(victim)
            || !GameFunctions.isPlayerAliveAndSurvival(attacker)) return false;

        if (gameWorld.isInnocent(attacker)) {
            replaceRole(serverVictim, gameWorld, false);
            killAttacker(attacker);
        } else if (gameWorld.canUseKillerFeatures(attacker)) {
            replaceRole(serverVictim, gameWorld, true);
            killAttacker(attacker);
        } else {
            killBoth(victim, spawnBody, attacker, deathReason);
        }
        return true;
    }

    private static void replaceRole(ServerPlayer player, GameWorldComponent gameWorld, boolean killerPool) {
        Role newRole = drawRole(killerPool);
        gameWorld.addRole(player, newRole);

        CompensatorComponent component = CompensatorComponent.KEY.get(player);
        if (component != null) component.reset();

        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, newRole);
        gameWorld.sync();
        player.setHealth(player.getMaxHealth());
        player.playNotifySound(
            SoundEvents.TOTEM_USE,
            SoundSource.PLAYERS,
            1.0f,
            1.0f
        );
        announceRole(player, gameWorld, newRole, killerPool);
    }

    private static Role drawRole(boolean killerPool) {
        ArrayList<Role> candidates = new ArrayList<>(WatheRoles.ROLES);
        candidates.removeIf(role ->
            Harpymodloader.VANNILA_ROLES.contains(role)
                || (killerPool ? !role.canUseKiller() : !role.isInnocent())
                || HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().getPath())
        );
        if (candidates.isEmpty()) {
            candidates.add(killerPool ? WatheRoles.KILLER : WatheRoles.CIVILIAN);
        }
        Collections.shuffle(candidates);
        return candidates.getFirst();
    }

    private static void announceRole(
        ServerPlayer player,
        GameWorldComponent gameWorld,
        Role role,
        boolean killerPool
    ) {
        RoleAnnouncementTexts.RoleAnnouncementText announcement = Harpymodloader.VANNILA_ROLES.contains(role)
            ? (killerPool ? RoleAnnouncementTexts.KILLER : RoleAnnouncementTexts.CIVILIAN)
            : Harpymodloader.autogeneratedAnnouncements.get(role);
        if (announcement == null) return;

        int announcementIndex = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(announcement);
        if (announcementIndex < 0) return;
        ServerPlayNetworking.send(
            player,
            new AnnounceWelcomePayload(announcementIndex, gameWorld.getAllKillerTeamPlayers().size(), 0)
        );
    }

    private static void killAttacker(Player attacker) {
        resolvingRetaliation = true;
        try {
            GameFunctions.killPlayer(attacker, true, null, GameConstants.DeathReasons.GENERIC);
        } finally {
            resolvingRetaliation = false;
        }
    }

    private static void killBoth(
        Player victim,
        boolean spawnBody,
        Player attacker,
        ResourceLocation deathReason
    ) {
        resolvingRetaliation = true;
        try {
            GameFunctions.killPlayer(attacker, true, victim);
            GameFunctions.killPlayer(
                victim,
                spawnBody,
                attacker,
                deathReason == null ? GameConstants.DeathReasons.GENERIC : deathReason
            );
        } finally {
            resolvingRetaliation = false;
        }
    }
}
