package cn.erindax.brinswathe.command;

import cn.erindax.brinswathe.BrinIcFlags;
import cn.erindax.brinswathe.BrinNoelleAccess;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.StringArgumentType;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;

public final class BrinPlayerCommands {
    private static final ResourceLocation VOODOO_DEATH =
        ResourceLocation.fromNamespaceAndPath("noellesroles", "voodoo");
    private static final String[] WANT_BE_ROLES = {"vulture", "executioner", "jester"};

    private BrinPlayerCommands() {
    }

    static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
        dispatcher.register(Commands.literal("killme").executes(context -> killme(context.getSource())));

        dispatcher.register(
            Commands.literal("iWantBe")
                .requires(source -> source.hasPermission(0))
                .then(Commands.argument("value", StringArgumentType.word())
                    .suggests((context, builder) -> {
                        String remaining = builder.getRemaining().toLowerCase();
                        for (String name : WANT_BE_ROLES) {
                            if (name.startsWith(remaining)) {
                                builder.suggest(name, Component.translatable("announcement.role.noellesroles." + name));
                            }
                        }
                        return builder.buildFuture();
                    })
                    .executes(context -> wantBe(
                        context.getSource(),
                        StringArgumentType.getString(context, "value")
                    )))
        );
    }

    private static int wantBe(CommandSourceStack source, String rawValue) {
        ServerPlayer player = source.getPlayer();
        if (player == null) {
            source.sendFailure(Component.literal("此指令只能由玩家执行"));
            return 0;
        }
        String value = rawValue.toLowerCase();
        GameWorldComponent game = GameWorldComponent.KEY.get(player.level());
        if (BrinNoelleAccess.initiateCount(game, player) > 1) {
            source.sendFailure(Component.literal("场上 Initiate 多于 1 人，无法自选职业"));
            return 0;
        }
        Role targetRole = BrinNoelleAccess.findRole(
            ResourceLocation.fromNamespaceAndPath("noellesroles", value)
        );
        if (targetRole == null) {
            source.sendFailure(Component.literal("无效角色: " + value + "(可选 vulture/executioner/jester)"));
            return 0;
        }
        clearItem(player, WatheItems.KNIFE);
        game.addRole(player, targetRole);
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, targetRole);
        announceRole(player, game, game.getRole(player));
        return 1;
    }

    private static void announceRole(ServerPlayer player, GameWorldComponent game, Role role) {
        if (role == null) return;
        RoleAnnouncementTexts.RoleAnnouncementText announcement = Harpymodloader.VANNILA_ROLES.contains(role)
            ? RoleAnnouncementTexts.KILLER
            : Harpymodloader.autogeneratedAnnouncements.get(role);
        if (announcement == null) return;
        int announcementIndex = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(announcement);
        if (announcementIndex < 0) return;
        ServerPlayNetworking.send(
            player,
            new AnnounceWelcomePayload(announcementIndex, game.getAllKillerTeamPlayers().size(), 0)
        );
    }

    private static void clearItem(Player player, net.minecraft.world.item.Item item) {
        for (int i = 0; i < player.getInventory().items.size(); i++) {
            ItemStack stack = player.getInventory().items.get(i);
            if (stack.is(item)) player.getInventory().items.set(i, ItemStack.EMPTY);
        }
        if (player.getInventory().offhand.getFirst().is(item)) {
            player.getInventory().offhand.set(0, ItemStack.EMPTY);
        }
    }

    private static int killme(CommandSourceStack source) {
        ServerPlayer player = source.getPlayer();
        if (player == null) {
            source.sendFailure(Component.literal("此指令只能由玩家执行"));
            return 0;
        }
        if (!BrinIcFlags.allowKillme) {
            source.sendFailure(Component.literal("killme 指令已被管理员禁用"));
            return 0;
        }
        GameFunctions.killPlayer(player, true, null, VOODOO_DEATH);
        return 1;
    }
}
